### ISSUE TITLE
About the code release

### ISSUE THREAD

**Issue by gentlefress** [AlessioSam/LADiff#1]
Dear author,

This is a wonderful work! Congratulations! I want to ask when will you release the code?

Best regards

**Comment by alesspalma** [comment]
Hi @gentlefress , thank you for the kind words!

The main code is already pushed in its entirety, it is just the repo's README which is under construction. To use our code, just place yourself in the `src` directory and follow the instructions of [MLD](https://github.com/ChenFengYe/motion-latent-diffusion) about how to run.

**Comment by gentlefress** [comment]
Dear author, 

Thank you for your reply! And can you release the pretrained VAE weights?

**Comment by alesspalma** [comment]
@gentlefress you can find it linked in the README. It is in the GDrive shared folder under DVAE/checkpoints.

**Comment by alesspalma** [comment]
Closing it as it seems resolved.
